#include "graphics/shader/recompiler/emitter/mslEmitterInternal.h"

#include <fmt/format.h>
#include <cmath>

namespace Libs::Graphics::ShaderRecompiler::Msl::Emitter {

std::string MslEmitterState::FormatOperand(const IR::Operand& op) {
	switch (op.kind) {
		case IR::OperandKind::ImmediateU32: {
			return fmt::format("{}u", op.imm);
		}
		case IR::OperandKind::Register:
			return FormatRegister(op.reg);
		default:
			return "0u";
	}
}

std::string MslEmitterState::FormatRegister(const IR::Register& reg) {
	switch (reg.file) {
		case IR::RegisterFile::Vector:
			return fmt::format("v{}", reg.index);
		case IR::RegisterFile::Scalar:
			return fmt::format("s{}", reg.index);
		case IR::RegisterFile::Exec:
			return "exec";
		case IR::RegisterFile::Vcc:
			return "vcc";
		case IR::RegisterFile::M0:
			return "m0";
		default:
			return fmt::format("reg_{}", reg.index);
	}
}

bool EmitModule(MslEmitterState& state, std::string& msl_source, std::string* error) {
	state.stage = state.program.stage;

	// 1. Headers & Preamble
	state.headers_ss << "// Generated by KytyPS5 Native MSL Emitter\n";
	state.headers_ss << "#include <metal_stdlib>\n";
	state.headers_ss << "using namespace metal;\n\n";

	// 2. PushConstants Struct
	state.structs_ss << "struct PushConstants {\n";
	state.structs_ss << "    uint user_data[64];\n";
	state.structs_ss << "    uint buffer_offsets[32];\n";
	state.structs_ss << "};\n\n";

	// 3. Stage Input/Output Structs
	if (state.stage == ShaderType::Vertex) {
		state.structs_ss << "struct VertexInput {\n";
		uint32_t attr_idx = 0;
		for (const auto& in : state.program.info.inputs) {
			if (in.kind == IR::StageInputKind::Parameter) {
				state.structs_ss << fmt::format("    float4 attr{} [[attribute({})]];\n", attr_idx, in.location);
				attr_idx++;
			}
		}
		if (attr_idx == 0) {
			state.structs_ss << "    float4 dummy_attr [[attribute(0)]];\n";
		}
		state.structs_ss << "};\n\n";

		state.structs_ss << "struct VertexOutput {\n";
		state.structs_ss << "    float4 position [[position]];\n";
		uint32_t out_loc = 0;
		for (const auto& out : state.program.info.outputs) {
			if (out.kind == IR::StageOutputKind::Parameter) {
				state.structs_ss << fmt::format("    float4 param{} [[user(loc{})]];\n", out.index, out.location);
				out_loc++;
			}
		}
		state.structs_ss << "};\n\n";
	} else if (state.stage == ShaderType::Pixel) {
		state.structs_ss << "struct FragmentInput {\n";
		state.structs_ss << "    float4 position [[position]];\n";
		state.structs_ss << "    bool front_facing [[front_facing]];\n";
		for (const auto& in : state.program.info.inputs) {
			if (in.kind == IR::StageInputKind::Parameter) {
				state.structs_ss << fmt::format("    float4 param{} [[user(loc{})]];\n", in.location, in.location);
			}
		}
		state.structs_ss << "};\n\n";

		state.structs_ss << "struct FragmentOutput {\n";
		uint32_t mrt_idx = 0;
		for (const auto& out : state.program.info.outputs) {
			if (out.kind == IR::StageOutputKind::Mrt) {
				state.structs_ss << fmt::format("    float4 color{} [[color({})]];\n", out.index, out.index);
				mrt_idx++;
			} else if (out.kind == IR::StageOutputKind::Depth) {
				state.structs_ss << "    float depth [[depth(any)]];\n";
			}
		}
		if (mrt_idx == 0) {
			state.structs_ss << "    float4 color0 [[color(0)]];\n";
		}
		state.structs_ss << "};\n\n";
	}

	// 4. Helper Functions
	state.helpers_ss << "inline uint mad24(uint a, uint b, uint c) { return a * b + c; }\n";
	state.helpers_ss << "inline int mad24(int a, int b, int c) { return a * b + c; }\n\n";

	// 5. Entry Point Function Header
	if (state.stage == ShaderType::Compute) {
		state.body_ss << "kernel void main0(\n";
		state.body_ss << "    uint3 thread_pos [[thread_position_in_grid]],\n";
		state.body_ss << "    uint3 threadgroup_pos [[threadgroup_position_in_grid]],\n";
		state.body_ss << "    uint3 thread_in_tg [[thread_position_in_threadgroup]],\n";
		state.body_ss << "    uint thread_index_in_tg [[thread_index_in_threadgroup]],\n";
		state.body_ss << "    constant PushConstants& push_constants [[buffer(0)]],\n";
		state.body_ss << "    device uint* storage_buffers [[buffer(1)]]\n";
		state.body_ss << ") {\n";
	} else if (state.stage == ShaderType::Vertex) {
		state.body_ss << "vertex VertexOutput main0(\n";
		state.body_ss << "    VertexInput in [[stage_in]],\n";
		state.body_ss << "    uint vertex_id [[vertex_id]],\n";
		state.body_ss << "    uint instance_id [[instance_id]],\n";
		state.body_ss << "    constant PushConstants& push_constants [[buffer(0)]],\n";
		state.body_ss << "    device uint* storage_buffers [[buffer(1)]]\n";
		state.body_ss << ") {\n";
		state.body_ss << "    VertexOutput out {};\n";
	} else if (state.stage == ShaderType::Pixel) {
		state.body_ss << "fragment FragmentOutput main0(\n";
		state.body_ss << "    FragmentInput in [[stage_in]],\n";
		state.body_ss << "    constant PushConstants& push_constants [[buffer(0)]],\n";
		state.body_ss << "    device uint* storage_buffers [[buffer(1)]]\n";
		state.body_ss << ") {\n";
		state.body_ss << "    FragmentOutput out {};\n";
	} else {
		state.body_ss << "kernel void main0() {\n";
	}

	// Local Threadgroup LDS Memory Allocation
	state.body_ss << "    threadgroup uint lds[16384];\n";

	// Register Allocations
	for (size_t i = 0; i < 256; ++i) {
		state.body_ss << fmt::format("    thread uint v{} = 0;\n", i);
	}
	for (size_t i = 0; i < 104; ++i) {
		state.body_ss << fmt::format("    thread uint s{} = 0;\n", i);
	}
	state.body_ss << "    thread uint vcc = 0;\n";
	state.body_ss << "    thread uint exec = 0xFFFFFFFFu;\n";
	state.body_ss << "    thread uint m0 = 0;\n\n";

	// 6. Block Instruction Loop
	for (size_t b = 0; b < state.program.blocks.size(); ++b) {
		const auto& block = state.program.blocks[b];
		state.body_ss << fmt::format("block_{}:\n", block.id);

		for (const auto& inst : block.instructions) {
			bool ok = false;
			ok = EmitAluOp(state, inst) ||
			     EmitControlFlowOp(state, inst) ||
			     EmitImageOp(state, inst) ||
			     EmitMemoryOp(state, inst) ||
			     EmitExportOp(state, inst);

			if (!ok) {
				state.has_unsupported_ops = true;
				std::string op_name = fmt::format("Opcode_{}", static_cast<int>(inst.op));
				state.unsupported_instructions.push_back(op_name);
				state.body_ss << fmt::format("    // Unsupported instruction: {}\n", op_name);
			}
		}
	}

	// Entry Point Return
	if (state.stage == ShaderType::Vertex || state.stage == ShaderType::Pixel) {
		state.body_ss << "    return out;\n";
	}
	state.body_ss << "}\n";

	// Assemble final MSL source
	msl_source = state.headers_ss.str() + state.structs_ss.str() + state.helpers_ss.str() + state.body_ss.str();
	return true;
}

} // namespace Libs::Graphics::ShaderRecompiler::Msl::Emitter
