// x86DecoderTables.cpp
//
// Definitions for Table-Driven x86-64 Decoder Opcode Lookup Tables.

#include "loader/recompiler/x86DecoderTables.h"

namespace Loader::Recompiler {

// 1-Byte Primary Opcode Table (0x00 - 0xFF)
const OpcodeEntry g_primary_opcode_table[256] = {
	/* 0x00 */ { X86Opcode::Add, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x01 */ { X86Opcode::Add, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x02 */ { X86Opcode::Add, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x03 */ { X86Opcode::Add, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x04 */ { X86Opcode::Add, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	/* 0x05 */ { X86Opcode::Add, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	/* 0x06 */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x07 */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x08 */ { X86Opcode::Or, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x09 */ { X86Opcode::Or, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x0A */ { X86Opcode::Or, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x0B */ { X86Opcode::Or, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x0C */ { X86Opcode::Or, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	/* 0x0D */ { X86Opcode::Or, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	/* 0x0E */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x0F */ { X86Opcode::Invalid, OpcodeFormat::TwoBytePrefix, 0, X86Condition::Equal, false },
	/* 0x10 */ { X86Opcode::Adc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x11 */ { X86Opcode::Adc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x12 */ { X86Opcode::Adc, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x13 */ { X86Opcode::Adc, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x14 */ { X86Opcode::Adc, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	/* 0x15 */ { X86Opcode::Adc, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	/* 0x16 */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x17 */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x18 */ { X86Opcode::Sbb, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x19 */ { X86Opcode::Sbb, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x1A */ { X86Opcode::Sbb, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x1B */ { X86Opcode::Sbb, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x1C */ { X86Opcode::Sbb, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	/* 0x1D */ { X86Opcode::Sbb, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	/* 0x1E */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x1F */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x20 */ { X86Opcode::And, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x21 */ { X86Opcode::And, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x22 */ { X86Opcode::And, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x23 */ { X86Opcode::And, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x24 */ { X86Opcode::And, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	/* 0x25 */ { X86Opcode::And, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	/* 0x26 */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x27 */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x28 */ { X86Opcode::Sub, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x29 */ { X86Opcode::Sub, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x2A */ { X86Opcode::Sub, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x2B */ { X86Opcode::Sub, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x2C */ { X86Opcode::Sub, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	/* 0x2D */ { X86Opcode::Sub, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	/* 0x2E */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x2F */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x30 */ { X86Opcode::Xor, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x31 */ { X86Opcode::Xor, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x32 */ { X86Opcode::Xor, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x33 */ { X86Opcode::Xor, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x34 */ { X86Opcode::Xor, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	/* 0x35 */ { X86Opcode::Xor, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	/* 0x36 */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x37 */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x38 */ { X86Opcode::Cmp, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x39 */ { X86Opcode::Cmp, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	/* 0x3A */ { X86Opcode::Cmp, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x3B */ { X86Opcode::Cmp, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	/* 0x3C */ { X86Opcode::Cmp, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	/* 0x3D */ { X86Opcode::Cmp, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	/* 0x3E */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x3F */ { X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x40 - 0x4F (REX Prefixes in 64-bit mode) */
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x50 - 0x57 (PUSH r64) */
	{ X86Opcode::Push, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Push, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Push, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Push, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Push, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Push, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Push, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Push, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	/* 0x58 - 0x5F (POP r64) */
	{ X86Opcode::Pop, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Pop, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Pop, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Pop, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Pop, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Pop, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Pop, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Pop, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	/* 0x60 - 0x6F */
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Reg_Mem, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Push, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	{ X86Opcode::Imul, OpcodeFormat::ModRm_Reg_Imm, 4, X86Condition::Equal, false },
	{ X86Opcode::Push, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	{ X86Opcode::Imul, OpcodeFormat::ModRm_Reg_Imm, 1, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x70 - 0x7F (Jcc rel8) */
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Overflow, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Overflow, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Carry, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Carry, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Equal, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Equal, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::BelowOrEqual, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::BelowOrEqual, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Sign, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Sign, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Parity, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Parity, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Less, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::Less, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::LessOrEqual, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 1, X86Condition::LessOrEqual, true },
	/* 0x80 - 0x8F (ModRM Group 1 & MOV / LEA) */
	{ X86Opcode::Add, OpcodeFormat::ModRm_Group, 1, X86Condition::Equal, false },
	{ X86Opcode::Add, OpcodeFormat::ModRm_Group, 4, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Add, OpcodeFormat::ModRm_Group, 1, X86Condition::Equal, false },
	{ X86Opcode::Test, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	{ X86Opcode::Test, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	{ X86Opcode::Lea, OpcodeFormat::ModRm_Reg_Mem, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Pop, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x90 - 0x9F (NOP, XCHG) */
	{ X86Opcode::Nop, OpcodeFormat::NoOperands, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0xA0 - 0xAF (MOV, MOVS, CMPS, TEST, STOS, LODS, SCAS) */
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Test, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	{ X86Opcode::Test, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0xB0 - 0xBF (MOV r8/r64, imm) */
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 4, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 4, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 4, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 4, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 4, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 4, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 4, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::RegEmbed, 4, X86Condition::Equal, false },
	/* 0xC0 - 0xCF (Shifts, RET, MOV rm, imm) */
	{ X86Opcode::Shl, OpcodeFormat::ModRm_Group, 1, X86Condition::Equal, false },
	{ X86Opcode::Shl, OpcodeFormat::ModRm_Group, 1, X86Condition::Equal, false },
	{ X86Opcode::Ret, OpcodeFormat::RelImm, 2, X86Condition::Equal, false },
	{ X86Opcode::Ret, OpcodeFormat::NoOperands, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Rm_Imm, 1, X86Condition::Equal, false },
	{ X86Opcode::Mov, OpcodeFormat::ModRm_Rm_Imm, 4, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0xD0 - 0xDF (Shifts Group 2) */
	{ X86Opcode::Shl, OpcodeFormat::ModRm_Group, 0, X86Condition::Equal, false },
	{ X86Opcode::Shl, OpcodeFormat::ModRm_Group, 0, X86Condition::Equal, false },
	{ X86Opcode::Shl, OpcodeFormat::ModRm_Group, 0, X86Condition::Equal, false },
	{ X86Opcode::Shl, OpcodeFormat::ModRm_Group, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0xE0 - 0xEF (JMP rel8/32, CALL rel32) */
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Call, OpcodeFormat::RelImm, 4, X86Condition::Equal, false },
	{ X86Opcode::Jmp, OpcodeFormat::RelImm, 4, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Jmp, OpcodeFormat::RelImm, 1, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0xF0 - 0xFF (Group 3 & Group 5) */
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Test, OpcodeFormat::ModRm_Group, 1, X86Condition::Equal, false },
	{ X86Opcode::Test, OpcodeFormat::ModRm_Group, 4, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Inc, OpcodeFormat::ModRm_Group, 0, X86Condition::Equal, false },
	{ X86Opcode::Inc, OpcodeFormat::ModRm_Group, 0, X86Condition::Equal, false }
};

// 2-Byte Opcode Table (0x0F 0x00 - 0x0F 0xFF)
const OpcodeEntry g_twobyte_opcode_table[256] = {
	/* 0x00 - 0x0F */
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x10 - 0x1F (SSE Movaps, Movups) */
	{ X86Opcode::Movups, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	{ X86Opcode::Movups, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	{ X86Opcode::Movaps, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	{ X86Opcode::Movaps, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x20 - 0x3F */
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Addps, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	{ X86Opcode::Subps, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	{ X86Opcode::Mulps, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	{ X86Opcode::Divps, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x40 - 0x4F (CMOVcc) */
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Overflow, false },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Overflow, true },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Carry, false },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Carry, true },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, true },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::BelowOrEqual, false },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::BelowOrEqual, true },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Sign, false },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Sign, true },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Parity, false },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Parity, true },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Less, false },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Less, true },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::LessOrEqual, false },
	{ X86Opcode::Cmov, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::LessOrEqual, true },
	/* 0x50 - 0x7F */
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	/* 0x80 - 0x8F (Jcc rel32) */
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Overflow, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Overflow, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Carry, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Carry, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Equal, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Equal, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::BelowOrEqual, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::BelowOrEqual, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Sign, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Sign, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Parity, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Parity, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Less, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::Less, true },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::LessOrEqual, false },
	{ X86Opcode::Jcc, OpcodeFormat::RelImm, 4, X86Condition::LessOrEqual, true },
	/* 0x90 - 0x9F (SETcc) */
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Overflow, false },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Overflow, true },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Carry, false },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Carry, true },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, false },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Equal, true },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::BelowOrEqual, false },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::BelowOrEqual, true },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Sign, false },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Sign, true },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Parity, false },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Parity, true },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Less, false },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::Less, true },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::LessOrEqual, false },
	{ X86Opcode::Setcc, OpcodeFormat::ModRm_Rm_Reg, 0, X86Condition::LessOrEqual, true },
	/* 0xA0 - 0xFF */
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Paddd, OpcodeFormat::ModRm_Reg_Rm, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false },
	{ X86Opcode::Invalid, OpcodeFormat::Invalid, 0, X86Condition::Equal, false }
};

} // namespace Loader::Recompiler
